DELETE FROM EMPRUNT;
DELETE FROM PRODUIT;

DELETE FROM PERSONNE;
DELETE FROM LIVRE;
DELETE FROM CD;
DELETE FROM DVD;
DELETE FROM GENRE;

DROP VIEW vue_cd;
DROP VIEW vue_dvd;
DROP VIEW vue_livre;
DROP VIEW vue_all_abonne;
DROP VIEW vue_all_employe;
DROP VIEW vue_all_gestionnaire;


DROP TABLE EMPRUNT;
DROP TABLE PRODUIT;

DROP TABLE PERSONNE;
DROP TABLE LIVRE;
DROP TABLE CD;
DROP TABLE DVD;
DROP TABLE GENRE;



DROP DATABASE gla_database;
